package com.fx.login.service;

import com.fx.login.model.*;
import com.fx.login.repo.PaymentCycleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Service
@Transactional
public class FeeGenerationService {

    @Autowired
    private PaymentCycleRepository paymentCycleRepository;

    @Autowired
    private UnpaidService unpaidService;

    @Autowired
    private ResidentService residentService;

    @Autowired
    private PaymentCycleService paymentCycleService;

    // ⏰ TỰ ĐỘNG CHẠY HÀNG NGÀY LÚC 00:30
    @Scheduled(cron = "0 30 0 * * *")
    public void autoGenerateDailyFees() {
        System.out.println("🔄 [" + LocalDate.now() + "] Bắt đầu kiểm tra chu kỳ tạo khoản thu...");

        try {
            List<PaymentCycleEntity> activeCycles = paymentCycleRepository.findByActiveTrue();

            for (PaymentCycleEntity cycle : activeCycles) {
                if (shouldGenerateToday(cycle)) {
                    generateFeesForCycle(cycle);
                }
            }

            System.out.println("✅ Hoàn thành kiểm tra chu kỳ tự động!");

        } catch (Exception e) {
            System.err.println("❌ Lỗi trong quá trình tự động tạo khoản thu: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Kiểm tra có nên tạo khoản thu hôm nay không
    private boolean shouldGenerateToday(PaymentCycleEntity cycle) {
        LocalDate today = LocalDate.now();
        LocalDate nextDue = cycle.getNextDue();

        return nextDue.equals(today) || nextDue.isBefore(today);
    }

    // TẠO KHOẢN THU CHO MỘT CHU KỲ (Manual trigger by admin)
    public List<UnpaidEntity> generateFeesForCycle(PaymentCycleEntity cycle) {
        System.out.println("📝 Tạo khoản thu cho chu kỳ: " + cycle.getFee().getFeeName());

        List<UnpaidEntity> newFees = new ArrayList<>();
        FeeEntity fee = cycle.getFee();

        List<Resident> residents = residentService.findAll();

        for (Resident resident : residents) {
            if (!isAlreadyGenerated(cycle, resident)) {
                UnpaidEntity unpaid = createUnpaidForResident(cycle, resident);
                UnpaidEntity savedUnpaid = unpaidService.createUnpaid(unpaid);
                newFees.add(savedUnpaid);
            }
        }

        // Cập nhật chu kỳ
        paymentCycleService.updateCycleAfterGeneration(cycle);

        System.out.println("✅ Đã tạo " + newFees.size() + " khoản thu mới");
        return newFees;
    }

    // Tạo khoản thu đột xuất (ONE_TIME)
    public List<UnpaidEntity> createOneTimeFees(FeeEntity fee, LocalDate dueDate, String description) {
        System.out.println("💰 Tạo khoản thu đột xuất: " + fee.getFeeName());

        List<UnpaidEntity> newFees = new ArrayList<>();
        List<Resident> residents = residentService.findAll();

        for (Resident resident : residents) {
            UnpaidEntity unpaid = new UnpaidEntity();
            unpaid.setFeeID(fee.getId());
            unpaid.setResidentName(resident.getFullName());
            unpaid.setApartmentName(resident.getApartmentNumber());
            unpaid.setTotalPayment(fee.getAmountDue());
            unpaid.setDueDate(dueDate.toString());
            unpaid.setStatus("PENDING");
            unpaid.setDescription(description != null ? description : "Khoản thu đột xuất - " + fee.getFeeName());

            UnpaidEntity savedUnpaid = unpaidService.createUnpaid(unpaid);
            newFees.add(savedUnpaid);
        }

        System.out.println("✅ Đã tạo " + newFees.size() + " khoản thu đột xuất");
        return newFees;
    }

    // Helper methods
    private boolean isAlreadyGenerated(PaymentCycleEntity cycle, Resident resident) {
        List<UnpaidEntity> existingFees = unpaidService.findByFeeID(cycle.getFee().getId());

        return existingFees.stream().anyMatch(unpaid ->
                resident.getFullName().equals(unpaid.getResidentName()) &&
                        resident.getApartmentNumber().equals(unpaid.getApartmentName()) &&
                        unpaid.getDueDate() != null &&
                        unpaid.getDueDate().equals(cycle.getNextDue().toString())
        );
    }

    private UnpaidEntity createUnpaidForResident(PaymentCycleEntity cycle, Resident resident) {
        FeeEntity fee = cycle.getFee();

        UnpaidEntity unpaid = new UnpaidEntity();
        unpaid.setFeeID(fee.getId());
        unpaid.setResidentName(resident.getFullName());
        unpaid.setApartmentName(resident.getApartmentNumber());
        unpaid.setTotalPayment(fee.getAmountDue());
        unpaid.setDueDate(cycle.getNextDue().toString());
        unpaid.setStatus("PENDING");
        unpaid.setDescription(createFeeDescription(fee, cycle));

        return unpaid;
    }

    private String createFeeDescription(FeeEntity fee, PaymentCycleEntity cycle) {
        String cycleDisplay = getCycleTypeDisplay(cycle.getCycleType());
        String period = generatePeriodDescription(cycle.getNextDue(), cycle.getCycleType());

        return String.format("Phí %s (%s) - %s",
                fee.getFeeName(),
                cycleDisplay,
                period
        );
    }

    private String getCycleTypeDisplay(String cycleType) {
        return switch (cycleType) {
            case "MONTHLY" -> "hàng tháng";
            case "QUARTERLY" -> "hàng quý";
            case "YEARLY" -> "hàng năm";
            case "ONE_TIME" -> "đột xuất";
            default -> cycleType;
        };
    }

    private String generatePeriodDescription(LocalDate dueDate, String cycleType) {
        return switch (cycleType) {
            case "MONTHLY" -> "Tháng " + dueDate.getMonthValue() + "/" + dueDate.getYear();
            case "QUARTERLY" -> "Quý " + ((dueDate.getMonthValue() - 1) / 3 + 1) + "/" + dueDate.getYear();
            case "YEARLY" -> "Năm " + dueDate.getYear();
            default -> dueDate.toString();
        };
    }
}